# Generated by Django 3.2.5 on 2021-07-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(db_index=True, max_length=70, verbose_name='Surname')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('middlename', models.CharField(blank=True, max_length=70, verbose_name='Middlename')),
                ('birth_date', models.DateField(verbose_name='BirthDate')),
                ('telephone_number', models.CharField(max_length=13, verbose_name='Telephone')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ('surname',),
            },
        ),
    ]
