# Generated by Django 3.2.5 on 2021-07-17 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['id', 'surname'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
    ]
