# Generated by Django 3.2.5 on 2021-07-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('category_name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('course_name',), 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_address',
            field=models.CharField(max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_birth_date',
            field=models.DateField(verbose_name='BirthDate'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_middlename',
            field=models.CharField(blank=True, max_length=70, verbose_name='Middlename'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_surname',
            field=models.CharField(db_index=True, max_length=70, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_telephone_number',
            field=models.CharField(max_length=13, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_available',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(db_index=True, max_length=70, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_price',
            field=models.DecimalField(decimal_places=2, help_text='Please enter price less than 10 000.00', max_digits=7, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_middlename',
            field=models.CharField(blank=True, max_length=70, verbose_name='Middlename'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(max_length=70, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_position',
            field=models.CharField(max_length=70, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_surname',
            field=models.CharField(db_index=True, max_length=70, verbose_name='Surname'),
        ),
    ]
