# Generated by Django 3.2.5 on 2021-07-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210715_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('surname',), 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('name',), 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('surname',), 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_birth_date',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_middlename',
            new_name='middlename',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_surname',
            new_name='surname',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_telephone_number',
            new_name='telephone_number',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_available',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employee_middlename',
            new_name='middlename',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employee_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employee_position',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employee_surname',
            new_name='surname',
        ),
    ]
