# Generated by Django 3.2.5 on 2021-07-16 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('main', '0003_auto_20210716_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='clients.client'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
