# Generated by Django 3.2.5 on 2021-07-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(db_index=True, max_length=70, verbose_name='Surname')),
                ('name', models.CharField(max_length=70, verbose_name='Name')),
                ('middlename', models.CharField(blank=True, max_length=70, verbose_name='Middlename')),
                ('position', models.CharField(max_length=70, verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['id', 'surname'],
            },
        ),
    ]
