# Generated by Django 3.2.8 on 2021-10-30 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_course_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='section_id',
            new_name='section',
        ),
    ]
